### ISSUE TITLE
Migrating Windows Forms Apps to .NET Core 3.0

### ISSUE THREAD

**Issue by kiranshahi** [kiranshahi/Employee-Management-System#13]
Microsoft recently announced .NET Core 3.0 that includes support for Windows Forms so, lets migrate this project to .NET Core 3.0.
https://devblogs.microsoft.com/dotnet/introducing-net-core-windows-forms-designer-preview-1/

[Guide to Migrating WPF Apps to .NET Core](https://docs.microsoft.com/en-us/dotnet/desktop-wpf/migration/convert-project-from-net-framework)

**Comment by SudhiR3369** [comment]
It is great to have .NET enthusiasts like you in github community. Thankyou for sharing this information.

**Comment by MarkusReynolds1989** [comment]
I'm quite interested, I will start working on this.

**Comment by kiranshahi** [comment]
@MarkusReynolds1989 Please, go on I have assigned this issue to you :)

**Comment by MarkusReynolds1989** [comment]
Ran into some issues with being able to test this on core 3 I don't have the option to target it. Already created csproj and migrated the packages

**Comment by kiranshahi** [comment]
@MarkusReynolds1989 what was the issue you ran into?

**Comment by MarkusReynolds1989** [comment]
I'm going to pull what I have and you can take a look when you have time :)

**Comment by InKahootz** [comment]
I think I could help as well! I'll submit some code and you can take a look at it.

**Comment by Venkat230407** [comment]
Let me also try on this.

**Comment by Varavchik18** [comment]
guys did you finsih upgrading to .net core 3.0?)
i want to upgrade it to at least net 5, so can somebody commit changes with 3.0 if it is done?
@kiranshahi if it is not, could you tell me it, i will try to do it even if it is not done yet

**Comment by kiranshahi** [comment]
@Varavchik18 Not upgraded to .net core 3.0. If you want you can port to .net 5.
