### ISSUE TITLE
Auto Increment an ID of employee

### ISSUE THREAD

**Issue by Varavchik18** [kiranshahi/Employee-Management-System#18]
For now, if i will create a two users with the same ID, they will exist together but it's not logical i suppose.
Also while we are importing a data from csv we need to validate do we have already an employee with the same ID and request to increment it or not to insert in table.

**Comment by ANCHITAYUSH** [comment]
Hi kiran can you please provide a document for the code setup.

**Comment by kiranshahi** [comment]
Hi @ANCHITAYUSH to run this project you need to install [SQL Server](https://www.microsoft.com/en-gb/sql-server/sql-server-downloads) and [Visual Studio](https://visualstudio.microsoft.com/).

Here are the few steps to run this project. 

- First of all clone the project. 
- Click on EmployeeManagementSystem.sln file. Basically, it will open the project in Visual Studio.
- Build EmployeeManagementSystem Project
- Before running the project, change the connection string in EmployeeManagementContext.cs file.

### Sln File.
![image](https://github.com/kiranshahi/Employee-Management-System/assets/15968059/b0f68884-1da7-4190-840d-50a589fecdbc)

### Project structure in Visual Studio
![image](https://github.com/kiranshahi/Employee-Management-System/assets/15968059/e9aa09ba-8fdf-46e0-897e-cbfd5d680841)

### Connection String
![image](https://github.com/kiranshahi/Employee-Management-System/assets/15968059/e74d2c60-c9ea-4012-a19a-22fae1f1cff6)


I hope this helped you. If you have any further question, feel free to ask.
