### ISSUE TITLE
Store CRUD operation data to database.

### ISSUE THREAD

**Issue by kiranshahi** [kiranshahi/Employee-Management-System#3]
Till now all the datas are stored to CSV file.

**Comment by DesmondANIMUS** [comment]
Hi, I'd like to try & contribute. Which DB should I use?

**Comment by LuckyN** [comment]
Interested can i pick any DB

**Comment by DesmondANIMUS** [comment]
Well, I know about SQLite & MongoDB so I could either use them or I could learn some new DB. So, I'll work on the db of your choice :)

**Comment by kiranshahi** [comment]
SQL Server is suitable for this project :) :+1:

**Comment by underfisk** [comment]
We're supposed to do a CRUD for db to import csv data ?

**Comment by lonestar1997** [comment]
which database your prefer more? Sql Server, MySQL, PostgresSql or NoSql

**Comment by kiranshahi** [comment]
@lonestar1997 its SQL Server

**Comment by kiranshahi** [comment]
@underfisk we are supposed to store data to db and import and export to CSV :)

**Comment by underfisk** [comment]
@kiranshahi i can help at the CRUD it isn't hard at all. I see you pretend to have a console or window app where you can insert with a CRUD in the db the data and export all from db to csv, is that right?

**Comment by kiranshahi** [comment]
@underfisk yes
